import time
import utils
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

browser = webdriver.Chrome()
browser.get('https://suikagame.io')
browser.switch_to.frame("iframehtml5")
time.sleep(2)
gameWindow = browser.find_element(By.XPATH, "/html/body/section")
action = ActionChains(browser)
action.move_to_element(gameWindow).move_by_offset(30,50).click().perform()
time.sleep(0.5)
action.move_to_element(gameWindow).move_by_offset(30,50).click().perform()
time.sleep(0.1)
utils.getPositions(browser)
time.sleep(0.1)
utils.getPositions(browser)
time.sleep(0.1)
utils.getPositions(browser)
time.sleep(0.1)
utils.getPositions(browser)
time.sleep(0.1)
utils.getPositions(browser)
time.sleep(2)
action.move_to_element(gameWindow).move_by_offset(5,0).click().perform()
time.sleep(0.1)
utils.getPositions(browser)
time.sleep(0.1)
utils.getPositions(browser)
time.sleep(0.1)
utils.getPositions(browser)
time.sleep(2)
utils.getPositions(browser)
utils.getCurrentFruit(browser)
utils.getScore(browser)
utils.getPositions(browser)
time.sleep(10)